#!/bin/bash

# Author: Robert Mitwicki
#
# Disable Nginx site

SITE=$1

EXPECTED_ARGS=1
ERROR_BARDARGS=128

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: `basename $0` site_name"
    exit $ERROR_BARDARGS
fi

if [ -L $SITE]; then
  rm /etc/nginx/sites-enabled/$SITE
else
  echo "Site does not exist or is not a symlink"
  echo "Enabled sites:"
  ls /etc/nginx/sites-enabled
  exit 1;
fi
