#!/bin/bash

# Author: Robert Mitwicki
#
# Disable Nginx site

SITE=$1
if [ -f $SITE ]; then
  rm /etc/nginx/sites-enabled/$SITE
else
  echo "Site does not exist"
  echo "Enabled sites:"
  ls /etc/nginx/sites-enabled
  exit 1;
fi
