#!/bin/bash

# Author: Robert Mitwicki
#
# Disable Nginx site

SITE=$1
if [ -L $SITE -a -z $SITE]; then
  rm /etc/nginx/sites-enabled/$SITE
else
  echo "Site does not exist or is not a symlink"
  echo "Enabled sites:"
  ls /etc/nginx/sites-enabled
  exit 1;
fi
